package ch.epfl.calendar.utils;

import java.io.IOException;
import java.net.ResponseCache;
import java.util.List;

import org.apache.http.Header;
import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.ResponseHandler;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.cookie.Cookie;
import org.apache.http.impl.client.AbstractHttpClient;
import org.apache.http.protocol.HttpContext;

import android.app.Activity;
import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import ch.epfl.calendar.apiInterface.CalendarClientException;

/**
 * This class contains several tools to work with http
 * @author AblionGE
 *
 */
public class HttpUtils {
    
    private static final int RESPONSE_OK = 200;
    
    private static final String EXCEPTION_LOCATION_MALFORMED = 
            "The location field is not well formed in the headers";
    
    /**
     * 
     * @param context the context of the {@link Activity} calling this method.
     * @return true if there is an internet connection on the android device. False, otherwise.
     */
    public static boolean isNetworkWorking(Context context) {
        ConnectivityManager connMgr = (ConnectivityManager) 
                context.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connMgr.getActiveNetworkInfo();
        return networkInfo != null && networkInfo.isConnected();
    }

    /**
     * Returns a {@link Cookie} stored in the {@link AbstractHttpClient} client with field field.
     * @param client the {@link AbstractHttpClient} to get the {@link Cookie} from.
     * @param field the field to look for in the {@link Cookie}.
     * @return
     */
    public Cookie getCookie(AbstractHttpClient client, String field) {
        if (client == null) {
            return null;
        }
        List<Cookie> lc = client.getCookieStore().getCookies();
        for (Cookie c : lc) {
            if (c.getName().equals(field)) {
                return c;
            }
        }
        return null;
    }
    
    /**
     * 
     * @param location the HTTP header in which we want to search the token.
     * @return the tequila token from an HTTP header
     * @throws ClientProtocolException
     */
    public String getTokenFromHeader(Header location) throws ClientProtocolException {
        if (location == null) {
            throw new ClientProtocolException("No Location field in the headers");
        }
        
        String tokenHeader = location.getValue();
        int i = tokenHeader.indexOf("=");
        if (i == -1) {
            throw new ClientProtocolException(EXCEPTION_LOCATION_MALFORMED);
        }
        return tokenHeader.substring(i+1);
    }
    
    /**
     * Throws a {@link CalendarClientException} if responseCode is different from 200.
     * @param responseCode the HTTP response code to check.
     * @throws CalendarClientException
     */
    public static void handleResponse(int responseCode) throws CalendarClientException {
        if (responseCode != RESPONSE_OK) {
            throw new CalendarClientException();
        }
    }
    
    /**
     * Executes a HTTP GET request
     * @param httpClient the {@link AbstractHttpClient} which will execute the request
     * @param get the request to execute.
     * @param context the {@link HttpContext} to use in the request.
     * @return the HTTP response returned as an answer to the request.
     * @throws ClientProtocolException
     * @throws IOException
     */
    public HttpResponse executeGet(AbstractHttpClient httpClient, HttpGet get, HttpContext context)
        throws ClientProtocolException, IOException {
        
        return httpClient.execute(get, context);
    }
    
    /**
     * Executes a HTTP POST request.
     * @param httpClient the {@link AbstractHttpClient} which will execute the request
     * @param post the request to execute.
     * @param handler the {@link ResponseHandler} to use
     * @return the response generated by the {@link ResponseHandler}
     * @throws ClientProtocolException
     * @throws IOException
     */
    public String executePost(AbstractHttpClient httpClient, HttpPost post, ResponseHandler<String> handler)
        throws ClientProtocolException, IOException {
        
        return httpClient.execute(post, handler);
    }
}
