application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /createCourse
  script: course.createCourse.application

- url: /getCourse
  script: course.getCourse.application